use crate::{
    feasts::KalendarEntry, holy_day::HolyDayId, liturgical_week::Cycle, Calendar, Feast,
    LiturgicalWeek, Rank, Season, Time, Weekday,
};

/// [Calendar](Calendar) that calculates dates from the liturgical and sanctoral calendar
/// of the 1979 Book of Common Prayer of The Episcopal Church.
pub const BCP1979_CALENDAR: Calendar = Calendar {
    easter_cycle_begins: 7,
    christmas_cycle_begins: 4,
    has_propers: true,
    weeks: &BCP1979_WEEKS,
    holy_days: &BCP1979_FEASTS,
    holy_day_ranks: &BCP1979_HOLY_DAY_RANKS,
    feast_seasons: &BCP1979_HOLY_DAY_SEASONS,
    week_seasons: &BCP1979_WEEK_SEASONS,
};

const BCP1979_WEEKS: [(Cycle, u8, LiturgicalWeek); 59] = [
    (Cycle::Advent, 0, LiturgicalWeek::LastPentecost),
    (Cycle::Advent, 1, LiturgicalWeek::Advent1),
    (Cycle::Advent, 2, LiturgicalWeek::Advent2),
    (Cycle::Advent, 3, LiturgicalWeek::Advent3),
    (Cycle::Advent, 4, LiturgicalWeek::Advent4),
    (Cycle::Christmas, 0, LiturgicalWeek::Christmas),
    (Cycle::Christmas, 1, LiturgicalWeek::Christmas1),
    (Cycle::Christmas, 2, LiturgicalWeek::Christmas2),
    (Cycle::Epiphany, 0, LiturgicalWeek::Epiphany),
    (Cycle::Epiphany, 1, LiturgicalWeek::Epiphany1),
    (Cycle::Epiphany, 2, LiturgicalWeek::Epiphany2),
    (Cycle::Epiphany, 3, LiturgicalWeek::Epiphany3),
    (Cycle::Epiphany, 4, LiturgicalWeek::Epiphany4),
    (Cycle::Epiphany, 5, LiturgicalWeek::Epiphany5),
    (Cycle::Epiphany, 6, LiturgicalWeek::Epiphany6),
    (Cycle::Epiphany, 7, LiturgicalWeek::Epiphany7),
    (Cycle::Epiphany, 8, LiturgicalWeek::Epiphany8),
    (Cycle::Easter, 0, LiturgicalWeek::LastEpiphany),
    (Cycle::Easter, 1, LiturgicalWeek::Lent1),
    (Cycle::Easter, 2, LiturgicalWeek::Lent2),
    (Cycle::Easter, 3, LiturgicalWeek::Lent3),
    (Cycle::Easter, 4, LiturgicalWeek::Lent4),
    (Cycle::Easter, 5, LiturgicalWeek::Lent5),
    (Cycle::Easter, 6, LiturgicalWeek::HolyWeek),
    (Cycle::Easter, 7, LiturgicalWeek::Easter),
    (Cycle::Easter, 8, LiturgicalWeek::Easter2),
    (Cycle::Easter, 9, LiturgicalWeek::Easter3),
    (Cycle::Easter, 10, LiturgicalWeek::Easter4),
    (Cycle::Easter, 11, LiturgicalWeek::Easter5),
    (Cycle::Easter, 12, LiturgicalWeek::Easter6),
    (Cycle::Easter, 13, LiturgicalWeek::Easter7),
    (Cycle::Easter, 14, LiturgicalWeek::Pentecost),
    (Cycle::Easter, 15, LiturgicalWeek::TrinitySunday),
    (Cycle::Easter, 16, LiturgicalWeek::Pentecost2),
    (Cycle::Easter, 17, LiturgicalWeek::Pentecost3),
    (Cycle::Easter, 18, LiturgicalWeek::Pentecost4),
    (Cycle::Easter, 19, LiturgicalWeek::Pentecost5),
    (Cycle::Easter, 20, LiturgicalWeek::Pentecost6),
    (Cycle::Easter, 21, LiturgicalWeek::Pentecost7),
    (Cycle::Easter, 22, LiturgicalWeek::Pentecost8),
    (Cycle::Easter, 23, LiturgicalWeek::Pentecost9),
    (Cycle::Easter, 24, LiturgicalWeek::Pentecost10),
    (Cycle::Easter, 25, LiturgicalWeek::Pentecost11),
    (Cycle::Easter, 26, LiturgicalWeek::Pentecost12),
    (Cycle::Easter, 27, LiturgicalWeek::Pentecost13),
    (Cycle::Easter, 28, LiturgicalWeek::Pentecost14),
    (Cycle::Easter, 29, LiturgicalWeek::Pentecost15),
    (Cycle::Easter, 30, LiturgicalWeek::Pentecost16),
    (Cycle::Easter, 31, LiturgicalWeek::Pentecost17),
    (Cycle::Easter, 32, LiturgicalWeek::Pentecost18),
    (Cycle::Easter, 33, LiturgicalWeek::Pentecost19),
    (Cycle::Easter, 34, LiturgicalWeek::Pentecost20),
    (Cycle::Easter, 35, LiturgicalWeek::Pentecost21),
    (Cycle::Easter, 36, LiturgicalWeek::Pentecost22),
    (Cycle::Easter, 37, LiturgicalWeek::Pentecost23),
    (Cycle::Easter, 38, LiturgicalWeek::Pentecost24),
    (Cycle::Easter, 39, LiturgicalWeek::Pentecost25),
    (Cycle::Easter, 40, LiturgicalWeek::Pentecost26),
    (Cycle::Easter, 41, LiturgicalWeek::Pentecost27),
];

const BCP1979_WEEK_SEASONS: [(LiturgicalWeek, Season); 31] = [
    (LiturgicalWeek::Advent1, Season::Advent),
    (LiturgicalWeek::Advent2, Season::Advent),
    (LiturgicalWeek::Advent3, Season::Advent),
    (LiturgicalWeek::Advent4, Season::Advent),
    (LiturgicalWeek::Christmas, Season::Christmas),
    (LiturgicalWeek::Christmas1, Season::Christmas),
    (LiturgicalWeek::Christmas2, Season::Christmas),
    (LiturgicalWeek::Epiphany, Season::Epiphany),
    (LiturgicalWeek::Epiphany1, Season::Epiphany),
    (LiturgicalWeek::Epiphany2, Season::Epiphany),
    (LiturgicalWeek::Epiphany3, Season::Epiphany),
    (LiturgicalWeek::Epiphany4, Season::Epiphany),
    (LiturgicalWeek::Epiphany5, Season::Epiphany),
    (LiturgicalWeek::Epiphany6, Season::Epiphany),
    (LiturgicalWeek::Epiphany7, Season::Epiphany),
    (LiturgicalWeek::Epiphany8, Season::Epiphany),
    (LiturgicalWeek::LastEpiphany, Season::Epiphany),
    (LiturgicalWeek::Lent1, Season::Lent),
    (LiturgicalWeek::Lent2, Season::Lent),
    (LiturgicalWeek::Lent3, Season::Lent),
    (LiturgicalWeek::Lent4, Season::Lent),
    (LiturgicalWeek::Lent5, Season::Lent),
    (LiturgicalWeek::HolyWeek, Season::HolyWeek),
    (LiturgicalWeek::Easter, Season::Easter),
    (LiturgicalWeek::Easter2, Season::Easter),
    (LiturgicalWeek::Easter3, Season::Easter),
    (LiturgicalWeek::Easter4, Season::Easter),
    (LiturgicalWeek::Easter5, Season::Easter),
    (LiturgicalWeek::Easter6, Season::Easter),
    (LiturgicalWeek::Easter7, Season::Ascension),
    (LiturgicalWeek::Pentecost, Season::Pentecost),
    // Algorithm defaults to Season::OrdinaryTime, so can ignore the season after Pentecost
    // This will (nominally, but not relevantly) reduce search times since this is O(n)
];

const BCP1979_HOLY_DAY_SEASONS: [(Feast, Season); 35] = [
    (Feast::ChristmasDay, Season::Christmas),
    (Feast::December29, Season::Christmas),
    (Feast::December30, Season::Christmas),
    (Feast::Epiphany, Season::Epiphany),
    (Feast::EveOfHolyCross, Season::HolyWeek),
    (Feast::FridayAfterAscension, Season::Ascension),
    (Feast::FridayInEasterWeek, Season::Easter),
    (Feast::GoodFriday, Season::HolyWeek),
    (Feast::FridayAfterAshWednesday, Season::Lent),
    (Feast::HolyCross, Season::HolyWeek),
    (Feast::HolyName, Season::Christmas),
    (Feast::January2, Season::Christmas),
    (Feast::January3, Season::Christmas),
    (Feast::January4, Season::Christmas),
    (Feast::MondayInEasterWeek, Season::Easter),
    (Feast::MondayInHolyWeek, Season::HolyWeek),
    (Feast::SaturdayAfterAscension, Season::Ascension),
    (Feast::EveOfPentecost, Season::Pentecost),
    (Feast::SaturdayInEasterWeek, Season::Easter),
    (Feast::HolySaturday, Season::HolyWeek),
    (Feast::SaturdayAfterAshWednesday, Season::Lent),
    (Feast::PalmSunday, Season::HolyWeek),
    (Feast::Pentecost, Season::Pentecost),
    (Feast::EveOfTrinitySunday, Season::Trinity),
    (Feast::TrinitySunday, Season::Trinity),
    (Feast::AscensionDay, Season::Ascension),
    (Feast::ThursdayInEasterWeek, Season::Easter),
    (Feast::MaundyThursday, Season::HolyWeek),
    (Feast::ThursdayAfterAshWednesday, Season::Lent),
    (Feast::TuesdayInEasterWeek, Season::Easter),
    (Feast::TuesdayInHolyWeek, Season::HolyWeek),
    (Feast::EveOfTheAscension, Season::Ascension),
    (Feast::WednesdayInEasterWeek, Season::Easter),
    (Feast::WednesdayInHolyWeek, Season::HolyWeek),
    (Feast::AshWednesday, Season::Lent),
];

const BCP1979_HOLY_DAY_RANKS: [(Feast, Rank); 86] = [
    (Feast::EveOfAllSaints, Rank::PrincipalFeast),
    (Feast::AllSaintsDay, Rank::PrincipalFeast),
    (Feast::ChristmasDay, Rank::PrincipalFeast),
    (Feast::ChristmasEve, Rank::PrincipalFeast),
    (Feast::EveOfEpiphany, Rank::PrincipalFeast),
    (Feast::Epiphany, Rank::PrincipalFeast),
    (Feast::EveOfHolyName, Rank::PrincipalFeast),
    (Feast::HolyName, Rank::PrincipalFeast),
    (Feast::EveOfPentecost, Rank::PrincipalFeast),
    (Feast::PalmSunday, Rank::PrincipalFeast),
    (Feast::EasterSunday, Rank::PrincipalFeast),
    (Feast::Pentecost, Rank::PrincipalFeast),
    (Feast::TrinitySunday, Rank::PrincipalFeast),
    (Feast::AscensionDay, Rank::PrincipalFeast),
    (Feast::EveOfTheAscension, Rank::PrincipalFeast),
    (Feast::EveOfEpiphany1, Rank::Sunday),
    (Feast::FridayInEasterWeek, Rank::PrecedenceOverHolyDay),
    (Feast::GoodFriday, Rank::PrecedenceOverHolyDay),
    (Feast::MondayInEasterWeek, Rank::PrecedenceOverHolyDay),
    (Feast::MondayInHolyWeek, Rank::PrecedenceOverHolyDay),
    (Feast::SaturdayInEasterWeek, Rank::PrecedenceOverHolyDay),
    (Feast::HolySaturday, Rank::PrecedenceOverHolyDay),
    (Feast::ThursdayInEasterWeek, Rank::PrecedenceOverHolyDay),
    (Feast::MaundyThursday, Rank::PrecedenceOverHolyDay),
    (Feast::TuesdayInEasterWeek, Rank::PrecedenceOverHolyDay),
    (Feast::TuesdayInHolyWeek, Rank::PrecedenceOverHolyDay),
    (Feast::WednesdayInEasterWeek, Rank::PrecedenceOverHolyDay),
    (Feast::WednesdayInHolyWeek, Rank::PrecedenceOverHolyDay),
    (Feast::AllSoulsDay, Rank::OptionalObservance),
    (Feast::Annunciation, Rank::HolyDay),
    (Feast::ConfessionOfStPeter, Rank::HolyDay),
    (Feast::ConversionOfStPaul, Rank::HolyDay),
    (Feast::EveOfHolyCross, Rank::HolyDay),
    (Feast::EveOfStJohnTheBaptist, Rank::HolyDay),
    (Feast::EveOfTheAnnunciation, Rank::HolyDay),
    (Feast::EveOfThePresentation, Rank::HolyDay),
    (Feast::EveOfTheTransfiguration, Rank::HolyDay),
    (Feast::EveOfTheVisitation, Rank::HolyDay),
    (Feast::FridayAfterAscension, Rank::PrecedenceOverWeekday),
    (Feast::FridayAfterAshWednesday, Rank::PrecedenceOverWeekday),
    (Feast::HolyCross, Rank::HolyDay),
    (Feast::HolyInnocents, Rank::HolyDay),
    (Feast::IndependenceDay, Rank::HolyDay),
    (Feast::NativityOfStJohnTheBaptist, Rank::HolyDay),
    (Feast::SaturdayAfterAscension, Rank::PrecedenceOverWeekday),
    (
        Feast::SaturdayAfterAshWednesday,
        Rank::PrecedenceOverWeekday,
    ),
    (Feast::PeterAndPaul, Rank::HolyDay),
    (Feast::PhilipAndJames, Rank::HolyDay),
    (Feast::SimonAndJude, Rank::HolyDay),
    (Feast::Andrew, Rank::HolyDay),
    (Feast::Barnabas, Rank::HolyDay),
    (Feast::Bartholomew, Rank::HolyDay),
    (Feast::James, Rank::HolyDay),
    (Feast::JamesOfJerusalem, Rank::HolyDay),
    (Feast::John, Rank::HolyDay),
    (Feast::Joseph, Rank::HolyDay),
    (Feast::Luke, Rank::HolyDay),
    (Feast::Mark, Rank::HolyDay),
    (Feast::MaryMagdalene, Rank::HolyDay),
    (Feast::Mary, Rank::HolyDay),
    (Feast::Matthew, Rank::HolyDay),
    (Feast::Matthias, Rank::HolyDay),
    (Feast::Michael, Rank::HolyDay),
    (Feast::Stephen, Rank::HolyDay),
    (Feast::Thomas, Rank::HolyDay),
    (Feast::EveOfTrinitySunday, Rank::HolyDay),
    (Feast::ThanksgivingDay, Rank::HolyDay),
    (Feast::ThePresentation, Rank::HolyDay),
    (Feast::TheTransfiguration, Rank::HolyDay),
    (Feast::TheVisitation, Rank::HolyDay),
    (
        Feast::ThursdayAfterAshWednesday,
        Rank::PrecedenceOverWeekday,
    ),
    (Feast::AshWednesday, Rank::HolyDay),
    (Feast::December24, Rank::PrecedenceOverWeekday),
    (Feast::December29, Rank::PrecedenceOverWeekday),
    (Feast::December30, Rank::PrecedenceOverWeekday),
    (Feast::December31, Rank::PrecedenceOverWeekday),
    (Feast::January2, Rank::PrecedenceOverWeekday),
    (Feast::January3, Rank::PrecedenceOverWeekday),
    (Feast::January4, Rank::PrecedenceOverWeekday),
    (Feast::January5, Rank::PrecedenceOverWeekday),
    (Feast::January7, Rank::PrecedenceOverWeekday),
    (Feast::January8, Rank::PrecedenceOverWeekday),
    (Feast::January9, Rank::PrecedenceOverWeekday),
    (Feast::January10, Rank::PrecedenceOverWeekday),
    (Feast::January11, Rank::PrecedenceOverWeekday),
    (Feast::January12, Rank::PrecedenceOverWeekday),
];

/// Array of all observances in the BCP 1979 calendar
pub const BCP1979_FEASTS: [KalendarEntry; 200] = [
    // Thanksgiving, Labor Day, All Saints’ Sunday
    (
        HolyDayId::DayOfMonth {
            month: 9,
            week: 1,
            day: Weekday::Mon,
        },
        Feast::LaborDay,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::DayOfMonth {
            month: 11,
            week: 4,
            day: Weekday::Thu,
        },
        Feast::ThanksgivingDay,
        Time::AllDay,
        None,
    ),
    // Special days
    (
        HolyDayId::SpecialDay(LiturgicalWeek::Epiphany, Weekday::Sat),
        Feast::EveOfEpiphany1,
        Time::EveningOnly,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::LastEpiphany, Weekday::Wed),
        Feast::AshWednesday,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::LastEpiphany, Weekday::Thu),
        Feast::ThursdayAfterAshWednesday,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::LastEpiphany, Weekday::Fri),
        Feast::FridayAfterAshWednesday,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::LastEpiphany, Weekday::Sat),
        Feast::SaturdayAfterAshWednesday,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::HolyWeek, Weekday::Sun),
        Feast::PalmSunday,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::HolyWeek, Weekday::Mon),
        Feast::MondayInHolyWeek,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::HolyWeek, Weekday::Tue),
        Feast::TuesdayInHolyWeek,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::HolyWeek, Weekday::Wed),
        Feast::WednesdayInHolyWeek,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::HolyWeek, Weekday::Thu),
        Feast::MaundyThursday,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::HolyWeek, Weekday::Fri),
        Feast::GoodFriday,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::HolyWeek, Weekday::Sat),
        Feast::HolySaturday,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::Easter, Weekday::Sun),
        Feast::EasterSunday,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::Easter, Weekday::Mon),
        Feast::MondayInEasterWeek,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::Easter, Weekday::Tue),
        Feast::TuesdayInEasterWeek,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::Easter, Weekday::Wed),
        Feast::WednesdayInEasterWeek,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::Easter, Weekday::Thu),
        Feast::ThursdayInEasterWeek,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::Easter, Weekday::Fri),
        Feast::FridayInEasterWeek,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::Easter, Weekday::Sat),
        Feast::SaturdayInEasterWeek,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::Easter6, Weekday::Wed),
        Feast::EveOfTheAscension,
        Time::EveningOnly,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::Easter6, Weekday::Thu),
        Feast::AscensionDay,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::Easter6, Weekday::Fri),
        Feast::FridayAfterAscension,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::Easter6, Weekday::Sat),
        Feast::SaturdayAfterAscension,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::Easter7, Weekday::Sat),
        Feast::EveOfPentecost,
        Time::EveningOnly,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::Pentecost, Weekday::Sun),
        Feast::Pentecost,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::Pentecost, Weekday::Sat),
        Feast::EveOfTrinitySunday,
        Time::EveningOnly,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::TrinitySunday, Weekday::Sun),
        Feast::TrinitySunday,
        Time::AllDay,
        None,
    ),
    // MM/DD feast days
    (HolyDayId::Date(1, 1), Feast::HolyName, Time::AllDay, None),
    (HolyDayId::Date(1, 2), Feast::January2, Time::AllDay, None),
    (HolyDayId::Date(1, 3), Feast::January3, Time::AllDay, None),
    (HolyDayId::Date(1, 4), Feast::January4, Time::AllDay, None),
    (
        HolyDayId::Date(1, 5),
        Feast::January5,
        Time::MorningOnly,
        None,
    ),
    (
        HolyDayId::Date(1, 5),
        Feast::EveOfEpiphany,
        Time::EveningOnly,
        None,
    ),
    (HolyDayId::Date(1, 6), Feast::Epiphany, Time::AllDay, None),
    (
        HolyDayId::Date(1, 7),
        Feast::January7,
        Time::AllDay,
        Some(LiturgicalWeek::Epiphany1),
    ),
    (
        HolyDayId::Date(1, 8),
        Feast::January8,
        Time::AllDay,
        Some(LiturgicalWeek::Epiphany1),
    ),
    (
        HolyDayId::Date(1, 9),
        Feast::January9,
        Time::AllDay,
        Some(LiturgicalWeek::Epiphany1),
    ),
    (
        HolyDayId::Date(1, 10),
        Feast::January10,
        Time::AllDay,
        Some(LiturgicalWeek::Epiphany1),
    ),
    (
        HolyDayId::Date(1, 10),
        Feast::WilliamLaud,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(1, 11),
        Feast::January11,
        Time::AllDay,
        Some(LiturgicalWeek::Epiphany1),
    ),
    (
        HolyDayId::Date(1, 12),
        Feast::January12,
        Time::AllDay,
        Some(LiturgicalWeek::Epiphany1),
    ),
    (
        HolyDayId::Date(1, 13),
        Feast::HilaryOfPoitiers,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(1, 17),
        Feast::AntonyOfEgypt,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(1, 18),
        Feast::ConfessionOfStPeter,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(1, 20), Feast::Fabian, Time::AllDay, None),
    (
        HolyDayId::Date(1, 21),
        Feast::AgnesAndCeciliaOfRome,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(1, 22),
        Feast::VincentOfSaragossa,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(1, 23),
        Feast::PhillipsBrooks,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(1, 25),
        Feast::ConversionOfStPaul,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(1, 26),
        Feast::TitusAndTimothy,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(1, 27),
        Feast::JohnChrysostom,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(1, 28),
        Feast::ThomasAquinas,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(2, 1),
        Feast::EveOfThePresentation,
        Time::EveningOnly,
        None,
    ),
    (
        HolyDayId::Date(2, 2),
        Feast::ThePresentation,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(2, 3), Feast::Anskar, Time::AllDay, None),
    (
        HolyDayId::Date(2, 5),
        Feast::TheMartyrsOfJapan,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(2, 13),
        Feast::AbsalomJones,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(2, 14),
        Feast::CyrilAndMethodius,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(2, 15),
        Feast::ThomasBray,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(2, 23),
        Feast::PolycarpOfSmyrna,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(2, 24), Feast::Matthias, Time::AllDay, None),
    (
        HolyDayId::Date(2, 27),
        Feast::GeorgeHerbert,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(3, 1),
        Feast::DavidOfWales,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(3, 2),
        Feast::ChadOfLichfield,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(3, 3),
        Feast::JohnAndCharlesWesley,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(3, 7),
        Feast::PerpetuaAndFelicity,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(3, 12),
        Feast::GregoryTheGreat,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(3, 17),
        Feast::PatrickOfIreland,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(3, 18),
        Feast::CyrilOfJerusalem,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(3, 19), Feast::Joseph, Time::AllDay, None),
    (HolyDayId::Date(3, 20), Feast::Cuthbert, Time::AllDay, None),
    (HolyDayId::Date(3, 21), Feast::ThomasKen, Time::AllDay, None),
    (
        HolyDayId::Date(3, 22),
        Feast::JamesDeKoven,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(3, 23),
        Feast::GregoryTheIlluminator,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(3, 24),
        Feast::EveOfTheAnnunciation,
        Time::EveningOnly,
        None,
    ),
    (
        HolyDayId::Date(3, 25),
        Feast::Annunciation,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(3, 27),
        Feast::CharlesHenryBrent,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(3, 29), Feast::JohnKeble, Time::AllDay, None),
    (HolyDayId::Date(3, 31), Feast::JohnDonne, Time::AllDay, None),
    (
        HolyDayId::Date(4, 1),
        Feast::FrederickDenisonMaurice,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(4, 2),
        Feast::JamesLloydBreck,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(4, 3),
        Feast::RichardOfChichester,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(4, 8),
        Feast::WilliamAugustusMuhlenberg,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(4, 9), Feast::WilliamLaw, Time::AllDay, None),
    (
        HolyDayId::Date(4, 11),
        Feast::GeorgeAugustusSelwyn,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(4, 19), Feast::Alphege, Time::AllDay, None),
    (
        HolyDayId::Date(4, 21),
        Feast::AnselmOfCanterbury,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(4, 25), Feast::Mark, Time::AllDay, None),
    (
        HolyDayId::Date(4, 29),
        Feast::CatherineOfSiena,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(5, 1),
        Feast::PhilipAndJames,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(5, 2),
        Feast::AthanasiusOfAlexandria,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(5, 4), Feast::Monica, Time::AllDay, None),
    (
        HolyDayId::Date(5, 8),
        Feast::JulianOfNorwich,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(5, 9),
        Feast::GregoryOfNazianzus,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(5, 19), Feast::Dunstan, Time::AllDay, None),
    (
        HolyDayId::Date(5, 20),
        Feast::AlcuinOfYork,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(5, 24),
        Feast::JacksonKemper,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(5, 25), Feast::Bede, Time::AllDay, None),
    (
        HolyDayId::Date(5, 26),
        Feast::AugustineOfCanterbury,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(5, 30),
        Feast::EveOfTheVisitation,
        Time::EveningOnly,
        None,
    ),
    (
        HolyDayId::Date(5, 31),
        Feast::TheVisitation,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(6, 1), Feast::Justin, Time::AllDay, None),
    (
        HolyDayId::Date(6, 3),
        Feast::TheMartyrsOfUganda,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(6, 5), Feast::Boniface, Time::AllDay, None),
    (
        HolyDayId::Date(6, 9),
        Feast::ColumbaOfIona,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(6, 10),
        Feast::EphremOfNisibis,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(6, 11), Feast::Barnabas, Time::AllDay, None),
    (
        HolyDayId::Date(6, 14),
        Feast::BasilOfCaesarea,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(6, 16),
        Feast::JosephButler,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(6, 18),
        Feast::BernardMizeki,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(6, 19),
        Feast::WulfstanOfWorcester,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(6, 22), Feast::Alban, Time::AllDay, None),
    (
        HolyDayId::Date(6, 23),
        Feast::EveOfStJohnTheBaptist,
        Time::EveningOnly,
        None,
    ),
    (
        HolyDayId::Date(6, 24),
        Feast::NativityOfStJohnTheBaptist,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(6, 28),
        Feast::IrenaeusOfLyons,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(6, 29),
        Feast::PeterAndPaul,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(7, 4),
        Feast::IndependenceDay,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(7, 11),
        Feast::BenedictOfNursia,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(7, 17),
        Feast::WilliamWhite,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(7, 22),
        Feast::MaryMagdalene,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(7, 24),
        Feast::ThomasAKempis,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(7, 25), Feast::James, Time::AllDay, None),
    (
        HolyDayId::Date(7, 27),
        Feast::WilliamReedHuntington,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(7, 30),
        Feast::WilliamWilberforce,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(7, 31),
        Feast::JosephOfArimathea,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(8, 5),
        Feast::EveOfTheTransfiguration,
        Time::EveningOnly,
        None,
    ),
    (
        HolyDayId::Date(8, 6),
        Feast::TheTransfiguration,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(8, 7),
        Feast::JohnMasonNeale,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(8, 8), Feast::Dominic, Time::AllDay, None),
    (
        HolyDayId::Date(8, 10),
        Feast::LaurenceOfRome,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(8, 11),
        Feast::ClareOfAssisi,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(8, 13),
        Feast::JeremyTaylor,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(8, 15), Feast::Mary, Time::AllDay, None),
    (
        HolyDayId::Date(8, 18),
        Feast::WilliamPorcherDubose,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(8, 20),
        Feast::BernardOfClairvaux,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(8, 24),
        Feast::Bartholomew,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(8, 25), Feast::Louis, Time::AllDay, None),
    (
        HolyDayId::Date(8, 28),
        Feast::AugustineOfHippo,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(8, 31),
        Feast::AidanOfLindisfarne,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(9, 2),
        Feast::TheMartyrsOfNewGuinea,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(9, 12),
        Feast::JohnHenryHobart,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(9, 13),
        Feast::CyprianOfCarthage,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(9, 13),
        Feast::EveOfHolyCross,
        Time::EveningOnly,
        None,
    ),
    (HolyDayId::Date(9, 14), Feast::HolyCross, Time::AllDay, None),
    (HolyDayId::Date(9, 16), Feast::Ninian, Time::AllDay, None),
    (
        HolyDayId::Date(9, 18),
        Feast::EdwardBouveriePusey,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(9, 19),
        Feast::TheodoreOfTarsus,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(9, 20),
        Feast::JohnColeridgePatteson,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(9, 21), Feast::Matthew, Time::AllDay, None),
    (
        HolyDayId::Date(9, 25),
        Feast::SergiusOfRadonezh,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(9, 26),
        Feast::LancelotAndrewes,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(9, 29), Feast::Michael, Time::AllDay, None),
    (HolyDayId::Date(9, 30), Feast::Jerome, Time::AllDay, None),
    (
        HolyDayId::Date(10, 1),
        Feast::RemigiusOfRheims,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(10, 4),
        Feast::FrancisOfAssisi,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(10, 6),
        Feast::WilliamTyndale,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(10, 9),
        Feast::RobertGrosseteste,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(10, 15),
        Feast::SamuelIsaacJosephScherechewsky,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(10, 16),
        Feast::HughLatimerAndNicholasRidley,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(10, 17),
        Feast::IgnatiusOfAntioch,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(10, 18), Feast::Luke, Time::AllDay, None),
    (
        HolyDayId::Date(10, 19),
        Feast::HenryMartyn,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(10, 23),
        Feast::JamesOfJerusalem,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(10, 26), Feast::Alfred, Time::AllDay, None),
    (
        HolyDayId::Date(10, 28),
        Feast::SimonAndJude,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(10, 29),
        Feast::JamesHannington,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(10, 31),
        Feast::EveOfAllSaints,
        Time::EveningOnly,
        None,
    ),
    (
        HolyDayId::Date(11, 1),
        Feast::AllSaintsDay,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(11, 2),
        Feast::AllSoulsDay,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(11, 3),
        Feast::RichardHooker,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(11, 7),
        Feast::Willibrord,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(11, 10),
        Feast::LeoOfRome,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(11, 11),
        Feast::MartinOfTours,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(11, 12),
        Feast::CharlesSimeon,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(11, 14),
        Feast::SamuelSeabury,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(11, 16),
        Feast::MargaretOfScotland,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(11, 17),
        Feast::HughOfLincoln,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(11, 18),
        Feast::HildaOfWhitby,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(11, 19),
        Feast::ElizabethOfHungary,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(11, 23),
        Feast::ClementOfRome,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(11, 30), Feast::Andrew, Time::AllDay, None),
    (
        HolyDayId::Date(12, 1),
        Feast::NicholasFerrar,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(12, 2),
        Feast::ChanningMooreWilliams,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(12, 4),
        Feast::JohnOfDamascus,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(12, 5),
        Feast::ClementOfAlexandria,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(12, 6),
        Feast::NicholasOfMyra,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(12, 7),
        Feast::AmbroseOfMilan,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(12, 21), Feast::Thomas, Time::AllDay, None),
    (
        HolyDayId::Date(12, 24),
        Feast::December24,
        Time::MorningOnly,
        None,
    ),
    (
        HolyDayId::Date(12, 24),
        Feast::ChristmasEve,
        Time::EveningOnly,
        None,
    ),
    (
        HolyDayId::Date(12, 25),
        Feast::ChristmasDay,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(12, 26), Feast::Stephen, Time::AllDay, None),
    (HolyDayId::Date(12, 27), Feast::John, Time::AllDay, None),
    (
        HolyDayId::Date(12, 28),
        Feast::HolyInnocents,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(12, 29),
        Feast::December29,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(12, 30),
        Feast::December30,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(12, 31),
        Feast::December31,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(12, 31),
        Feast::EveOfHolyName,
        Time::EveningOnly,
        None,
    ),
];

#[cfg(test)]
mod tests {
    use crate::LiturgicalDayId;

    use super::super::*;

    #[test]
    fn thanksgiving_day() {
        let tday = BCP1979_CALENDAR.liturgical_day(Date::from_ymd(2021, 11, 25), false);
        assert_eq!(
            tday.observed,
            LiturgicalDayId::Feast(Feast::ThanksgivingDay)
        );
        let tday = BCP1979_CALENDAR.liturgical_day(Date::from_ymd(2017, 11, 23), false);
        assert_eq!(
            tday.observed,
            LiturgicalDayId::Feast(Feast::ThanksgivingDay)
        );
    }

    #[test]
    fn last_week_after_epiphany() {
        let tday = BCP1979_CALENDAR
            .liturgical_day_without_transferred_feasts(Date::from_ymd(2022, 2, 28), false);
        assert_eq!(
            tday.observed,
            LiturgicalDayId::WeekAndDay(LiturgicalWeek::LastEpiphany, Weekday::Mon)
        );
    }
}
