use liturgy::Document;

lazy_static! {
    pub static ref LITURGIES: Vec<(&'static str, &'static Document)> = vec![
        ("morning-prayer", &library::rite2::office::MORNING_PRAYER_II),
        ("noonday-prayer", &library::rite2::office::NOONDAY_PRAYER),
        ("compline", &library::rite2::office::COMPLINE),
    ];
    pub static ref CANTICLES: Vec<(&'static str, &'static Document)> = vec![
        ("canticle/1", &library::rite1::canticles::CANTICLE_1),
        ("canticle/2", &library::rite1::canticles::CANTICLE_2),
        ("canticle/3", &library::rite1::canticles::CANTICLE_3),
        ("canticle/4", &library::rite1::canticles::CANTICLE_4),
        ("canticle/5", &library::rite1::canticles::CANTICLE_5),
        ("canticle/6", &library::rite1::canticles::CANTICLE_6),
        ("canticle/7", &library::rite1::canticles::CANTICLE_7),
        ("canticle/8", &library::rite2::canticles::CANTICLE_8),
        ("canticle/9", &library::rite2::canticles::CANTICLE_9),
        ("canticle/10", &library::rite2::canticles::CANTICLE_10),
        ("canticle/11", &library::rite2::canticles::CANTICLE_11),
        ("canticle/12", &library::rite2::canticles::CANTICLE_12),
        ("canticle/13", &library::rite2::canticles::CANTICLE_13),
        ("canticle/14", &library::rite2::canticles::CANTICLE_14),
        ("canticle/15", &library::rite2::canticles::CANTICLE_15),
        ("canticle/16", &library::rite2::canticles::CANTICLE_16),
        ("canticle/17", &library::rite2::canticles::CANTICLE_17),
        ("canticle/18", &library::rite2::canticles::CANTICLE_18),
        ("canticle/19", &library::rite2::canticles::CANTICLE_19),
        ("canticle/20", &library::rite2::canticles::CANTICLE_20),
        ("canticle/21", &library::rite2::canticles::CANTICLE_21),
        ("canticle/12-eow", &library::eow::canticles::CANTICLE_12_EOW),
        ("canticle/15-eow", &library::eow::canticles::CANTICLE_15_EOW),
        ("canticle/16-eow", &library::eow::canticles::CANTICLE_16_EOW),
        ("canticle/18-eow", &library::eow::canticles::CANTICLE_18_EOW),
        ("canticle/21-eow", &library::eow::canticles::CANTICLE_21_EOW),
        ("canticle/a", &library::eow::canticles::CANTICLE_A),
        ("canticle/b", &library::eow::canticles::CANTICLE_B),
        ("canticle/c", &library::eow::canticles::CANTICLE_C),
        ("canticle/d", &library::eow::canticles::CANTICLE_D),
        ("canticle/e", &library::eow::canticles::CANTICLE_E),
        ("canticle/f", &library::eow::canticles::CANTICLE_F),
        ("canticle/g", &library::eow::canticles::CANTICLE_G),
        ("canticle/h", &library::eow::canticles::CANTICLE_H),
        ("canticle/i", &library::eow::canticles::CANTICLE_I),
        ("canticle/j", &library::eow::canticles::CANTICLE_J),
        ("canticle/k", &library::eow::canticles::CANTICLE_K),
        ("canticle/l", &library::eow::canticles::CANTICLE_L),
        ("canticle/m", &library::eow::canticles::CANTICLE_M),
        ("canticle/n", &library::eow::canticles::CANTICLE_N),
        ("canticle/o", &library::eow::canticles::CANTICLE_O),
        ("canticle/p", &library::eow::canticles::CANTICLE_P),
        ("canticle/q", &library::eow::canticles::CANTICLE_Q),
        ("canticle/r", &library::eow::canticles::CANTICLE_R),
        ("canticle/s", &library::eow::canticles::CANTICLE_S),
    ];
}
