[package]
name = "library"
version = "0.1.0"
edition = "2018"

[dependencies]
lazy_static = '1.0'
lectionary = { path = "../lectionary" }
liturgy = { path = "../liturgy" }
calendar = { path = "../calendar" }
psalter = { path = "../psalter" }
reference-parser = { path = "../reference-parser" }
serde = { version = "1", features = ["derive"]}